// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokeBinder.Infrastructure;

#nullable disable

namespace PokeBinder.Infrastructure.Migrations
{
    [DbContext(typeof(PokeBinderDbContext))]
    [Migration("20260716213117_AddPricingDomain")]
    partial class AddPricingDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PokeBinder.Core.Binders.Binder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColourHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int>("Columns")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rows")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId", "LastAccessedAt");

                    b.ToTable("Binders");
                });

            modelBuilder.Entity("PokeBinder.Core.Binders.BinderPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BinderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BinderId", "PageNumber")
                        .IsUnique();

                    b.ToTable("BinderPages");
                });

            modelBuilder.Entity("PokeBinder.Core.Binders.BinderSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CardVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Condition")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid?>("OverlayTagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Owned")
                        .HasColumnType("bit");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardVariantId");

                    b.HasIndex("OverlayTagId");

                    b.HasIndex("PageId", "Position")
                        .IsUnique();

                    b.ToTable("BinderSlots");
                });

            modelBuilder.Entity("PokeBinder.Core.Binders.OverlayTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColourHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique();

                    b.ToTable("OverlayTags");
                });

            modelBuilder.Entity("PokeBinder.Core.Cards.Card", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Abilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Artist")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Attacks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ConvertedRetreatCost")
                        .HasColumnType("int");

                    b.Property<string>("EvolvesFrom")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FlavorText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hp")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("HpValue")
                        .HasColumnType("int");

                    b.Property<string>("ImageLargeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageSmallUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Legalities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("NumberSortGroup")
                        .HasColumnType("tinyint");

                    b.Property<string>("NumberSortPrefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NumberSortSuffix")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("NumberSortValue")
                        .HasColumnType("int");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Rarity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegulationMark")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Resistances")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RetreatCost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subtypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supertype")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Types")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weaknesses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Artist");

                    b.HasIndex("ConvertedRetreatCost");

                    b.HasIndex("HpValue");

                    b.HasIndex("Name");

                    b.HasIndex("Rarity");

                    b.HasIndex("RegulationMark");

                    b.HasIndex("SetId");

                    b.HasIndex("Supertype");

                    b.HasIndex("SetId", "NumberSortGroup", "NumberSortPrefix", "NumberSortValue", "NumberSortSuffix")
                        .HasDatabaseName("IX_Card_Set_NumberSortKey");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("PokeBinder.Core.Cards.CardEditAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChangedFields")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditedByEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EditedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("EditedAt");

                    b.ToTable("CardEditAudits");
                });

            modelBuilder.Entity("PokeBinder.Core.Cards.CardPokedexNumber", b =>
                {
                    b.Property<string>("CardId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("CardId", "Number");

                    b.HasIndex("Number");

                    b.ToTable("CardPokedexNumbers");
                });

            modelBuilder.Entity("PokeBinder.Core.Cards.CardResistanceType", b =>
                {
                    b.Property<string>("CardId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CardId", "Type");

                    b.HasIndex("Type");

                    b.ToTable("CardResistanceTypes");
                });

            modelBuilder.Entity("PokeBinder.Core.Cards.CardSubtype", b =>
                {
                    b.Property<string>("CardId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subtype")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CardId", "Subtype");

                    b.HasIndex("Subtype");

                    b.ToTable("CardSubtypes");
                });

            modelBuilder.Entity("PokeBinder.Core.Cards.CardType", b =>
                {
                    b.Property<string>("CardId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CardId", "Type");

                    b.HasIndex("Type");

                    b.ToTable("CardTypes");
                });

            modelBuilder.Entity("PokeBinder.Core.Cards.CardVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("VariantTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VariantTypeId");

                    b.HasIndex("CardId", "VariantTypeId")
                        .IsUnique();

                    b.ToTable("CardVariants");
                });

            modelBuilder.Entity("PokeBinder.Core.Cards.CardWeaknessType", b =>
                {
                    b.Property<string>("CardId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CardId", "Type");

                    b.HasIndex("Type");

                    b.ToTable("CardWeaknessTypes");
                });

            modelBuilder.Entity("PokeBinder.Core.Cards.Set", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Legalities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("PrintedTotal")
                        .HasColumnType("int");

                    b.Property<string>("PtcgoCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SymbolImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseDate");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("PokeBinder.Core.Cards.SyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CardsAdded")
                        .HasColumnType("int");

                    b.Property<int>("CardsProcessed")
                        .HasColumnType("int");

                    b.Property<int>("CardsUpdated")
                        .HasColumnType("int");

                    b.Property<string>("ChangedFieldCounts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RemainingManualConflicts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RunByEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RunByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SetsAdded")
                        .HasColumnType("int");

                    b.Property<int>("SetsProcessed")
                        .HasColumnType("int");

                    b.Property<int>("SetsUpdated")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalSets")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("SyncRuns");
                });

            modelBuilder.Entity("PokeBinder.Core.Cards.VariantType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VariantTypes");
                });

            modelBuilder.Entity("PokeBinder.Core.Collection.CardOwnership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Condition")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CardVariantId");

                    b.HasIndex("UserId", "CardVariantId")
                        .IsUnique();

                    b.ToTable("CardOwnerships");
                });

            modelBuilder.Entity("PokeBinder.Core.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PokeBinder.Core.Pricing.CardVariantScrapeState", b =>
                {
                    b.Property<Guid>("CardVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastScrapedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScrapePriority")
                        .HasColumnType("int");

                    b.HasKey("CardVariantId");

                    b.HasIndex("ScrapePriority", "LastScrapedAt");

                    b.ToTable("CardVariantScrapeStates");
                });

            modelBuilder.Entity("PokeBinder.Core.Pricing.ClassificationFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CorrectedValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ListingClassificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OriginalGuessJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ListingClassificationId");

                    b.ToTable("ClassificationFeedbacks");
                });

            modelBuilder.Entity("PokeBinder.Core.Pricing.ListingClassification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BestOfferAccepted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ClassifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("int");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("GradedStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Grader")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IdentityMatchStrong")
                        .HasColumnType("bit");

                    b.Property<string>("KillReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RawCondition")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<Guid>("RawListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResolvedCardVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VariantMatch")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("RawListingId")
                        .IsUnique();

                    b.HasIndex("ResolvedCardVariantId");

                    b.HasIndex("Status");

                    b.ToTable("ListingClassifications");
                });

            modelBuilder.Entity("PokeBinder.Core.Pricing.PricePoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AggregatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CardVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Condition")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("DeliveredMedianGbp")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("GradedStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Grader")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ItemOnlyMedianGbp")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("LastSaleDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaxGbp")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MinGbp")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("QuarantinedReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SampleCount")
                        .HasColumnType("int");

                    b.Property<int>("WindowDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardVariantId", "Condition", "WindowDays")
                        .IsUnique()
                        .HasDatabaseName("IX_PricePoints_Raw_Bucket")
                        .HasFilter("[GradedStatus] = 'Raw'");

                    b.HasIndex("CardVariantId", "Grader", "Grade", "WindowDays")
                        .IsUnique()
                        .HasDatabaseName("IX_PricePoints_Graded_Bucket")
                        .HasFilter("[GradedStatus] = 'Graded'");

                    b.ToTable("PricePoints");
                });

            modelBuilder.Entity("PokeBinder.Core.Pricing.RawListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ItemPriceGbp")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ListingFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ListingId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("PostagePriceGbp")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("SoldDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CardVariantId");

                    b.HasIndex("ListingId", "SourceProvider")
                        .IsUnique();

                    b.ToTable("RawListings");
                });

            modelBuilder.Entity("PokeBinder.Core.Pricing.ScrapeRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CardsProcessed")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ListingsAccepted")
                        .HasColumnType("int");

                    b.Property<int>("ListingsFound")
                        .HasColumnType("int");

                    b.Property<int>("ListingsQuarantined")
                        .HasColumnType("int");

                    b.Property<int>("ListingsRejected")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TriggeredByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("ScrapeRuns");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PokeBinder.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PokeBinder.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeBinder.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PokeBinder.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokeBinder.Core.Binders.BinderPage", b =>
                {
                    b.HasOne("PokeBinder.Core.Binders.Binder", "Binder")
                        .WithMany("Pages")
                        .HasForeignKey("BinderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Binder");
                });

            modelBuilder.Entity("PokeBinder.Core.Binders.BinderSlot", b =>
                {
                    b.HasOne("PokeBinder.Core.Cards.CardVariant", "CardVariant")
                        .WithMany()
                        .HasForeignKey("CardVariantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokeBinder.Core.Binders.OverlayTag", "OverlayTag")
                        .WithMany()
                        .HasForeignKey("OverlayTagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PokeBinder.Core.Binders.BinderPage", "Page")
                        .WithMany("Slots")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardVariant");

                    b.Navigation("OverlayTag");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("PokeBinder.Core.Cards.Card", b =>
                {
                    b.HasOne("PokeBinder.Core.Cards.Set", "Set")
                        .WithMany("Cards")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("PokeBinder.Core.Cards.CardEditAudit", b =>
                {
                    b.HasOne("PokeBinder.Core.Cards.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("PokeBinder.Core.Cards.CardPokedexNumber", b =>
                {
                    b.HasOne("PokeBinder.Core.Cards.Card", "Card")
                        .WithMany("PokedexNumbers")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("PokeBinder.Core.Cards.CardResistanceType", b =>
                {
                    b.HasOne("PokeBinder.Core.Cards.Card", "Card")
                        .WithMany("ResistanceTypeRows")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("PokeBinder.Core.Cards.CardSubtype", b =>
                {
                    b.HasOne("PokeBinder.Core.Cards.Card", "Card")
                        .WithMany("SubtypeRows")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("PokeBinder.Core.Cards.CardType", b =>
                {
                    b.HasOne("PokeBinder.Core.Cards.Card", "Card")
                        .WithMany("TypeRows")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("PokeBinder.Core.Cards.CardVariant", b =>
                {
                    b.HasOne("PokeBinder.Core.Cards.Card", "Card")
                        .WithMany("Variants")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeBinder.Core.Cards.VariantType", "VariantType")
                        .WithMany()
                        .HasForeignKey("VariantTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("VariantType");
                });

            modelBuilder.Entity("PokeBinder.Core.Cards.CardWeaknessType", b =>
                {
                    b.HasOne("PokeBinder.Core.Cards.Card", "Card")
                        .WithMany("WeaknessTypeRows")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("PokeBinder.Core.Collection.CardOwnership", b =>
                {
                    b.HasOne("PokeBinder.Core.Cards.CardVariant", "CardVariant")
                        .WithMany()
                        .HasForeignKey("CardVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardVariant");
                });

            modelBuilder.Entity("PokeBinder.Core.Pricing.CardVariantScrapeState", b =>
                {
                    b.HasOne("PokeBinder.Core.Cards.CardVariant", null)
                        .WithMany()
                        .HasForeignKey("CardVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokeBinder.Core.Pricing.ClassificationFeedback", b =>
                {
                    b.HasOne("PokeBinder.Core.Pricing.ListingClassification", "ListingClassification")
                        .WithMany()
                        .HasForeignKey("ListingClassificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListingClassification");
                });

            modelBuilder.Entity("PokeBinder.Core.Pricing.ListingClassification", b =>
                {
                    b.HasOne("PokeBinder.Core.Pricing.RawListing", "RawListing")
                        .WithMany()
                        .HasForeignKey("RawListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RawListing");
                });

            modelBuilder.Entity("PokeBinder.Core.Binders.Binder", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("PokeBinder.Core.Binders.BinderPage", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("PokeBinder.Core.Cards.Card", b =>
                {
                    b.Navigation("PokedexNumbers");

                    b.Navigation("ResistanceTypeRows");

                    b.Navigation("SubtypeRows");

                    b.Navigation("TypeRows");

                    b.Navigation("Variants");

                    b.Navigation("WeaknessTypeRows");
                });

            modelBuilder.Entity("PokeBinder.Core.Cards.Set", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
